### ISSUE TITLE
HTTPS Switch is URGENT

### ISSUE THREAD

**Issue by imnvr** [madvas/ethlance#13]
Hello, a site running on http and not https, seems like a lack of care for security, which severely degrades credibility of the platform. 

This should be something you proceed to do ASAP !

**Comment by madvas** [comment]
Hi, 
Since we're running in 100% decentralised manner on public Ethereum blockchain, using `https` gains no reasonable security benefit to our platform. No passwords or private data are transferred at any point. 
Anyways, I've tried to setup `https` some time ago, but since we're serving files from decentralised IPFS, it's not so simple. If you have experience with setting up `https` with IPFS, help is more than welcome. I will try to take a look at it again tho.

**Comment by imnvr** [comment]
I understand but you don't lose anything from doing that, it gives people a better sense of security, most people don't know what you just told me.

**Comment by madvas** [comment]
Yep I'm aware of that. As I said, I've already tried to set it up with IPFS, but unsuccessfully. Will try to give it some more time.
