### ISSUE TITLE
Escrow Service

### ISSUE THREAD

**Issue by imnvr** [madvas/ethlance#14]
Is Escrow Service something that you offer ? It makes total sense to protect both the buyer and the seller.

**Comment by madvas** [comment]
Right now we don't have escrow service (with kind of exception being sponsored jobs). Escrow service doesn't provide much value unless you have an authority resolving disputes. We don't want be single centralised authority to resolve users' disputes. In future we want to provide decentralised approach to solve this problem, but right now it is still on a drawing board. Meanwhile, our freelancers are allowed to send invoices to their employers as frequently as they want, so that allows for continuous payments as work is progressed. This should greatly mitigate risk of not getting paid for lot of work.
